### ISSUE TITLE
[BUG] Out of sync with About Time

### ISSUE THREAD

**Issue by rmasoni** [vigoren/foundryvtt-simple-calendar#105]
**Describe the bug**
Importing from About Time doesn't give the same date. I have the correct date on About Time (151-5-3) and Simple Calendar shows another (151-6-4). Setting the correct date and exporting to About Time doesn't do anything. Also, I always have the time stopped, so it probably isn't that.

**To Reproduce**
1. Import calendar from About Time into Simple Calendar
2. See error

**Expected behavior**
The date should be the exact same on both ends when integrated.

**Screenshots**
<img width="620" alt="image" src="https://user-images.githubusercontent.com/62244/119258394-d274db80-bb9f-11eb-8603-956df03268a6.png">

**Browser (please complete the following information):**
 - OS: macOS 11.3.1
 - Browser: Chrome
 - Browser Version: 90.0.4430.212

**Comment by rmasoni** [comment]
It seems like after a refresh the exported calendar takes place on About Time.

**Comment by vigoren** [comment]
Yeah this is related to a [bug in about time](https://github.com/unsoluble/smalltime/issues/29#issuecomment-845913270) that Simple Calendar tried to fix  by adjusting a setting in about time. apparently the way to get the setting change to take in about time is with a refresh. 

Not much else i can do until it's fixed in about time unfortunately.

At least it's easy to get it working.
