### ISSUE TITLE
[FEATURE] Pin Compact calendar in place

### ISSUE THREAD

**Issue by thatlonelybugbear** [vigoren/foundryvtt-simple-calendar#153]
**Is your feature request related to a problem? Please describe.**
Keep needing to re-open the calendar and compact it every time the game reloads.

**Describe the solution you'd like**
A way to pin the compact calendar open to a specific location

**Describe alternatives you've considered**
The Calendar/Weather solution to that.

**Comment by Symon-S** [comment]
I second this motion :+1:

**Comment by apoapostolov** [comment]
I will voice an unpopular opinion. Feel free to flame me, if needed.

SmallTime has almost perfected the UI/UX for a clock widget and is offering scene darkness control. It is already dependent on SimpleCalendar for calendar data management since the big About Time update. This is already an ecosystem of time and date management tools.

Why not focus on the full calendar management, and a fantasy-calendar.com functionality internal to Foundry, instead of trying to replicate the same work on a screen static widget?

**Comment by vigoren** [comment]
I tend to agree with @apoapostolov. While I do intended to do a user interface update in the future where this will be apart of it there are other priorities for me to finish with the calendar first. Especially with other modules, like small time, that provide a nice clean interface already.
