### ISSUE TITLE
Tie-in with About Time and Calendar/Weather

### ISSUE THREAD

**Issue by baileymh** [vigoren/foundryvtt-simple-calendar#16]
First off, excellent work on this module! I came from Fantasy Grounds and having a calendar view with the option to add date-specific notes was missed. Hugely appreciated!

Not sure if this is already something you are planning or intending, but I also use Calendar/Weather with About Time. It's nice to be able to easily progress the time and day, and have things trigger by time of day. Would it be possible for your module to sync up with them? To where the day for Simple Calendar progresses at the same rate?

**Comment by ariakas2008** [comment]
I'd suggest just to add a time tracker, without syncing up. Easier and less overkill then C/W+About Time.

**Comment by vigoren** [comment]
I can look into doing both.

A time tracker built into this calendar.
Or if a user chooses (via a setting) and the modules are installed I can look into hooking into the About Time tracking.

That said I haven't looked into what is all involved in setting this up so it may be a bit of time before this feature is ready and the about time tie in might get cut if it ends up being too involved.

**Comment by baileymh** [comment]
Thanks! 
From what I've looked, the documentation for About Time is fairly thorough. So hopefully it won't be too difficult.

**Comment by Jonwh25** [comment]
I love this module a lot. It is my experience that this module replaces the "Calendar/Weather" module that is done by DasSauerkraut.   It basically does the same thing minus the about-time addition and then adds all the things unique to this module.  I think the time tracker idea is cool though and the sync with about-time. Those make sense.

**Comment by tposney** [comment]
If you are looking at integration the simplest is via the core feature
```
game.time.worldTime
```
 and/or
```
game.settings.set("core", "time", seconds);
```
Which is where the core software store the time, in seconds since 0.   
About time uses it's calendar definitions to define what 0 seconds means as a date time and then maintains y/m/d/h/m/s -> seconds and updates the world time.  
So the simplest integration would be setting the game time.  
The next integration could be matching the simple calendar calendar definitions with about-time calendar definitions and updating about-time with the new calendar and then the time would just "work".  
I could help out with an import function for about-time to pull in simple-calendar calendar definitions and then they would just work together - if you're interested and if not no problem.

**Comment by vigoren** [comment]
Thanks for the information. I'm going to bump this up in the priority queue as most people seem to be waiting for the tie into the game time.

So I'll focus on getting the game time and calendar times to sync up and a way to import from the calendar\weather system.

I appreciate the offer for help though I have all ready been thinking on how to do it and it shouldn't be very hard to get out quickly.

I do appreciate all the feedback 😁

**Comment by vigoren** [comment]
I have tied in Simple Calendar to the game world time so it updates that and gets updated by changes to it, this allows for a nice integration with about-time (and by extension Calendar/Weather). 

Simple Calendar also now has its own time tracker so as real world seconds go by the game time can advance (by how much is configurable). This time tracker is paused when the game is paused and it also pauses when a combat has started and increments each round of combat by the number of seconds for a round (for D&D/Pathfinder that is 6 seconds). So it should work with effect tracking modules though that is not 100% tested.

I have also gotten importing settings from about-time and calendar/weather into Simple Calendar working as well as exporting settings from Simple Calendar into about-time and calendar/weather working, with some caveats due to issues in the other modules. More details about that can be seen [here](https://github.com/vigoren/foundryvtt-simple-calendar/issues/39#issuecomment-801635635)

Getting this all set up was a bit of work but it is now on to testing/clean up. I also want to add a couple more things before making a new release but this will be out in the wild soon I hope.

**Comment by baileymh** [comment]
Fantastic work Vigoren! Looking forward to the update. Keep up the hard work, it is very much appreciated!

**Comment by vigoren** [comment]
Sorry this took so long but this should be all good to go in the 1.2.0 release.

I have heard that the author of Calendar/Weather is no longer updating that module so importing those settings in Simple Calendar might be a better way to go instead of using both.
