### ISSUE TITLE
[BUG] Combat rounds don't increment time in some systems.

### ISSUE THREAD

**Issue by vigoren** [vigoren/foundryvtt-simple-calendar#167]
Some systems don't update the game time as combat round pass (pf1e as an example). While other systems do (dnd5e).

Need to look into providing a way to specify how many seconds should pass per combat round and how this interacts with systems that all ready update the game time.

**Comment by STBaf** [comment]
Since this has passed to Released, should the latest Release 1.3.39 only bring up a setting or is this already working ? I just checked with the DS4 Game System (which, as far as I know does not provide any time information die Foundry) and on starting a combat round clock keeps "normally" running. My expectation was that the normal passing of time would be stopped and then the set seconds time would be added per combat round (by the way, this is how the Calender/Weather addon (in conjunction with About Time) behaved). However, I may have misunderstood what should happen when you switch to combat mode in a system without time information, then sorry!

**Comment by vigoren** [comment]
@STBaf 

Yes this is working.

The clock only stops running when the active Scene (will have a target icon next to its name) has an active combat (requires at least 1 token to be apart of the combat). I do this so that if another scene has a combat in it that you forgot about the calendar doesn't refuse to start the clock because of that. This way only the currently active scene is checked for combats.

With that criteria met then the clock will pause and as combat rounds end time will be added to the clock.

When the combat is finished the clock will start running again.

**Comment by STBaf** [comment]
I tried to reproduce that und made a video from the behavior beneath DS4:
https://www.youtube.com/watch?v=5c7zLBmLI3o
still not working

I'am using Foundry 0.8,9 and used to reproduce my DS4 Test enviromnemt with 4 enabled modules which are:
libwrapper (0.10.5.0, dependency of Perfect Vision)
Perfect Vision (2.9.7)
SimpleCalender (1.3.39 obviously)
SmallTime (1.11.4)

**Comment by karpana** [comment]
I too was having the same trouble with the clock not working with/during combat  iwth the lateste update, though I don't ujse the "running clock in the background" configuration (I manage all non-combat time in other wasy using the forward/back buttons in the time controls).

Knowing that only the active scene will move combat time forward has resolved my issues.

I might suggest that this be noted somewhere (either in the documentation or maybe right on the settings).

In any case.
Thank you!!
