### ISSUE TITLE
[BUG] gregorian calendar inaccurate to reality

### ISSUE THREAD

**Issue by miromonti** [vigoren/foundryvtt-simple-calendar#171]
Simple Calendar's Gregorian calendar is inaccurate to reality:
![image](https://user-images.githubusercontent.com/38819125/126717230-e45321d5-a9d1-451b-88ce-bc726f362c03.png)
I also checked the moon phases and they're also incorrect. Aligning this calendar with real life would be lovely.

I'm not sure how to reproduce the behavior. I set up Simple Calendar for the first time for my Deadlands game. I changed the year to 1879 and started entering notes. Along the way, I set the Gregorian leap year rule and added our one moon. I thought nothing of the default settings, figuring everything is standard stuff.

Then I looked up 1879 in reality to coincide holidays. That's when I saw Simple Calendar was off by two days. I advanced to current day just to see what would show and that's the image I captured above.

Naturally, this is not game-breaking. I doubt any of my players will consider the year and realize that May 23 was actually a Friday. But this inaccuracy is now real for me and I'll always think about it. 

Is there a way to reset the calendar or otherwise flush the settings to start anew? Or a way to "nudge" dates would be also be great.

Since I run my Foundry game via The Forge, I checked on three browsers. The inaccuracy is the same on all.
- Chrome 91.0.4472.164
- Edge 91.0.864.71
- Firefox 90.0.2

**Comment by vigoren** [comment]
Hey, the Gregorian calendar is accurate to real life if set up correctly. Turning on the Gregorian leap year is not all that is needed to set it up correctly for real life.

The easiest way to set up the Gregorian calendar to be accurate is to use the predefined calendar setting for it. It won't remove your notes just adjust the calendar settings to set it up correctly.

Otherwise you will need to set these settings to get it to reflect reality (as this is how the calendar works in reality). This is assuming the months and weekdays are set correctly already

### Year Settings

**Year Zero**: 1970

### Weekday Settings

**Starting Week Day**: Thursday

### Leap Year Settings

**Leap Year Rule**: Gregorian
Adjust February to have 29 days instead of 28.

### Moon Settings
Add a moon.
**Cycle Length**: 29.53059
**Cycle Adjustment**: 0.5
**Reference Moon Year Reset**: Do not reset reference year
**New Moon Year**: 2000
**New Moon Month**: January
**New Moon Day**: 6

The Phases should not need adjustment


Setting all of those should result in the calendar aligning with the real one. Or the far easier approach is use the Gregorian predefined calendar as that will set all of this up for you, then you can just change the current year to 1879.

One thing to note is the calculation I use for when the moon phase is only accurate to plus or minus 1 day of when it actually occurs. So it may not be 100% accurate but it will be within 1 day of when it actually occurs.

**Comment by miromonti** [comment]
Thanks for your prompt response. I followed your instructions and the calendar result is wrong:
![image](https://user-images.githubusercontent.com/38819125/126724018-0364cd84-47f5-4590-90f4-02a935fee33b.png)
[Dateandtime.com](https://www.timeanddate.com/calendar/?year=1970&country=1) and [Calendar-365.com](https://www.calendar-365.com/1970-calendar.html) both say that the July 1 1970 is on Wednesday, not Monday. However, the moon phases are correct.

Maybe I missed something, or a setting that I don't know about is awry. Here's what I have:
![image](https://user-images.githubusercontent.com/38819125/126724211-567db37b-98bc-41da-9cbd-ccca8a5685fb.png)
![image](https://user-images.githubusercontent.com/38819125/126724427-384c8fa9-fbfb-48d3-93f5-bdbff249bf2c.png)
![image](https://user-images.githubusercontent.com/38819125/126724222-4a26d010-775a-4706-b65b-45a57863e124.png)
![image](https://user-images.githubusercontent.com/38819125/126724235-b18c13a4-5f40-4b61-833e-2fa1e5011c95.png)
![image](https://user-images.githubusercontent.com/38819125/126724524-d26ebabd-7c5a-440c-a1c1-60a012720edd.png)
![image](https://user-images.githubusercontent.com/38819125/126724250-b6f67841-6164-4134-9c92-9dcd771f5b62.png)

**Comment by vigoren** [comment]
You missed the **Year Zero** setting under Year Settings, it should be 1970 not 0. It is below the year prefix/postfix fields.

**Comment by miromonti** [comment]
Great! That fixed it. Thanks for your patience.

**Comment by vigoren** [comment]
No problem glad it's working 😁
