### ISSUE TITLE
[FEATURE] agree with Small Time on which tool bar "time" goes

### ISSUE THREAD

**Issue by scooper4711** [vigoren/foundryvtt-simple-calendar#193]
Simple Calendar places itself under Token Controls.
Smalltime places itself under Journal Notes.

Arguments could be made for either or neither of those options. One might even argue that the concept of "time" is a "measurement" and belongs under that tool set.

Regardless of where you two place yourself, I'd love it if you were both under the *same* tool set. :D

**Comment by scooper4711** [comment]
Link to https://github.com/unsoluble/smalltime/issues/77

**Comment by vigoren** [comment]
I have been thinking about this, unsoluble is correct in that I put it under Token Controls because it has the most visibility. I also put it under there to match the Pathfinder 2E systems built in world clock (which also lives under Token Controls).

I can see the argument for having it under Journal Notes, I mean I list Simple Calendar under the "Journal and Notes" category of modules.

I fear though that I have trained everyone to look for SC under Token controls and moving it would cause a lot of confusion so I think for the time being I am going to leave it where it is. I think ideally I would like to have it under its own control category, but not sure if that would ever happen.

**Comment by vigoren** [comment]
I have changed this in version 2.1.0 of Simple Calendar. It now lives under the Journal Notes as I think it now fits better under there.
