### ISSUE TITLE
[BUG] Undefined string in german world clock

### ISSUE THREAD

**Issue by Hasenhirn** [vigoren/foundryvtt-simple-calendar#201]
**Describe the bug**
undefined string in d/m/y in world clock

**To Reproduce**
1. start a new world and activate simple calendar
2. add modules pf2e german and babele
3. open world clock

**Expected behavior**
correct display of d/m/y without the undefined string

**Screenshots**
![No undefined](https://i.imgur.com/iHPfDfQ.png)
![Undefined](https://i.imgur.com/Gxylfjx.png)

**Foundry Information**
 - Foundry Version: 0.8.9
 - Game System: PF2E german
 - Simple Calendar Configuration: PF2e Calendar

**Browser (please complete the following information):**
 - OS: Win10
 - Browser Edge / Chromium
 - Browser Version 93.0.961.38

**Comment by vigoren** [comment]
Hey based on your screenshots the issue is with the built in world clock of pathfinder 2e not simple calendar.

That dialog isn't simple calendars and I am pretty certain that the PF2E world clock does not pull any information from simple calendar.

Your best bet would be to bring it up to the PF2E system developers.

**Comment by Hasenhirn** [comment]
sorry for the mixup!
