### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Freewolf2000** [vigoren/foundryvtt-simple-calendar#206]
So I am running with the Eberron calendar, and I am loading up the Moons into the calendar. There are twelve moons so lot's of moons show up on the calendar.

What seems to be more problematic is that sometimes a moon phase will appear over the course of 2 days, rather than just one.
I have New Moon, Full Moon, First Quarter, Last Quarter all set to be 1 day phase lengths.

The odd thing is that this is not consistent. Some times a New Moon will appear on just one day, and others it will appear over two days on the calendar. Is there a way to force it to appear only on one day during a calendar month to reduce the clutter that will appear in the calendar from the moons?

**Comment by vigoren** [comment]
This is an issue of rounding. I use a simplified equation for determining the moons phase that is based on finding the moons phase for our Gregorian calendar.

This equation for our Gregorian calendar breaks each cycle into equal length phases (about 3 days each). My changes attempt to adjust theses phases so some only appear on a single day. The problem is that due to the lack of precision and rounding sometimes a single day phase will say it appears on two days.

The best way to combat this is to add more decimal places to the moons cycle length or use the Cycle adjustment field to help with fine tuning things (the cycle adjust field should be a number between 0 and 1 in most cases).

In project 1.5.x I plan to look closer at my formulas and try to fix them in these rounding instances but I haven't started on them yet.

Math is fun, especially when looking at astronomical equations 😁 haha

**Comment by Freewolf2000** [comment]
Thank you for that, I was able to add in a bunch of decimals and got this to work out for me.

And for the record, thanks so much for mathing. =) This is a really awesome tool and I appreciate the work that you have put into this.

**Comment by vigoren** [comment]
Glad that helped out!
