### ISSUE TITLE
[Traveller: Imperial Calendar - SceneData Darkness "NaN"] 

### ISSUE THREAD

**Issue by RicoMittelholzer** [vigoren/foundryvtt-simple-calendar#232]
**SceneData Darkness "NaN" is not a number between 0 and 1**

Using Cerpheus Traveller System, Simple Calendar, Day Night Cycle and Weather Control. Pregen Calendar is set to Traveller: Imperial Calendar. When changing Time (pass a day) the error pops out. SceneData Darkness "NaN" is not a number between 0 and 1.

It only happens on Calendars: Gregorian, and Traveller: Imperial Calendar. 

Day Night Cycle dont change Darkness at all.

**Expected behavior**
Like when playing Forbidden Lands, using the pregen FL Calendar, it works like a charme. only at Traveller and all Gregorian there seem to be a Problem.

**Screenshots**
<img width="2200" alt="Bildschirmfoto 2021-10-06 um 21 30 07" src="https://user-images.githubusercontent.com/57154644/136270622-45aeabe6-7d55-4411-af62-062d4be1deeb.png">

**Foundry Information**
 - Foundry Version: [0.8.9]
 - Game System: [Twodsix - Cerpheus, Traveller 0.8.15]
 - Simple Calendar Configuration: [Pregenerated Traveller]

**Additional context**
had a big discussion with SDoehren from Day Night Cycle. We did a lot of testing at Foundry Console but could not find a way to fix it. 

<img width="587" alt="Bildschirmfoto_2021-10-06_um_20 52 51" src="https://user-images.githubusercontent.com/57154644/136271200-b8b01ad2-d274-4356-bb1f-639cc253babe.png">

Tested all commands at console like:
Foundry VTT | Retrieved and compiled template modules/weather-control/templates/calendar.html
foundry.js:3601 Foundry VTT | Retrieved and compiled template modules/compendium-folders/templates/compendium-directory.html
SimpleCalendar.api.dateToTimestamp({year:0,month:0,day:0,hour:0,minute:1,second:0});
60
SimpleCalendar.api.dateToTimestamp({year:0,month:0,day:0,hour:1,minute:0,second:0});
3600
SimpleCalendar.api.dateToTimestamp({year:0,month:0,day:1,hour:0,minute:0,second:0});
0

**Comment by SDoehren** [comment]
Hi RicoMittelholzer was sent over by me as Day Night Cycle is mine and I couldn't solve the issue.

`SimpleCalendar.api.dateToTimestamp({year:0,month:0,day:1,hour:0,minute:0,second:0})
`

works in all calendars I have seen expect this one use case with RicoMittelholzer but SimpleCalendar.api.getTimeConfiguration() should resolve this regardless.

**Comment by vigoren** [comment]
the getTimeConfiguration is the better way to go.

dateToTimestamp works on calendars other than the Gregorian and Traveller one because all other calendars have a year zero (the reference year for generating timestamps) of zero and their first month has more than 1 day in it.

Since dateToTimestamp is converting the passed in date to a timestamp it takes into account the year zero. For Gregorian calendars that is 1970 (the epoch) so asking to get the timestamp for a date before January 1 1970 will result in a negative number, which is hour our real world timestamp numbers work.

Because the month and day parameter of the date are indexs not the numerical representation of the month when asking for month 0 and day 1 you are really asking for the second day of the first month, which in the case of the Traveller calendar the first month only has 1 day so it maxes out at 1 day, or in index of 0. Since Traveller has a year zero of 0, then finding difference between the first day of year zero and Holiday 1, year 0 (also the first day of year zero) results in 0.

So that function is working as intended.

Hope that helps explain things a little.
