### ISSUE TITLE
[FEATURE] add new calendar

### ISSUE THREAD

**Issue by eunaumtenhoid** [vigoren/foundryvtt-simple-calendar#303]
hi dude?
how can i upload a new rpg calendar to stay in the default calendar options? for version 2.0

**Comment by vigoren** [comment]
I will be adding a contribution guide for that if it is something that you want to be apart of the module and share with everyone.

If you want to modify the files just for your installed version of Simple Calendar you can follow these steps. It requires a little bit of JSON file copy and pasting)

**Important** These files will be overwritten on updates to SC so your changes would be lost after an update. It is best to make these changes then save the files some where else. After updating Simple Calendar you can copy these modified files back over to get your own custom calendar back.

- Create the calendar in Simple Calendar.
- Export the calendars configuration (just the configuration, not the permissions or global configuration). If you added holiday notes then export the notes as well.
- Create a new JSON file and call it the name of your calendar. eg new-calendar.json and give it this content
```json
{
  "calendar":{},
  "notes":[]
}
```
- The export file should look something like this
```json
{
  "exportVersion":2,
  "globalConfig":{},
  "permissions":{},
  "calendars":[
    {...}
  ],
  "notes":{
    "default":[...]
  }
}
```
- You will want to copy the object from the calendars array to the calendar property of new-calendar.json
- You will want to copy the array of notes from notes.default in the export file to the notes property of new-calendar.json
- This file will then be placed in the `FoundryVTT\Data\modules\foundryvtt-simple-calendar\predefined-calendars` folder of the installed module.
- In that folder, there is a file called `calendar-list.json`, we will need to edit that. Open that file.
- You will see a list of calendars, to the list you will want to add
```json
{
  {"key": "new-calendar", "label": "My New Calendar", "config":  true, "notes":  false}
}
```
  - Where the key is the name of the file (minus the .json)
  - notes is only true if the new-calendar.json has notes in it, otherwise leave it false.
  - Reload foundry and your new calendar should appear in the list of predefined calendars under quick setup.

Hope that answers your question!
