### ISSUE TITLE
[BUG] When trying to update, version 1.3.75 shows "Current"

### ISSUE THREAD

**Issue by Shuggaloaf** [vigoren/foundryvtt-simple-calendar#315]
**Describe the bug**
When clicking the update button in FVTT's module page, it doesn't update and tells me that v1.3.75 is current. 

I know this is probably something unique as I haven't seen this reported by others. Just wondering if you may have any idea of what to try? I know I can export calendar, uninstall/reinstall, just trying to avoid if possible. 

**To Reproduce**
I think the description above satisfies this section. 

**Screenshots**
![image](https://user-images.githubusercontent.com/79543184/167693752-aa7b4dfe-e954-48cd-ba34-7d8f6c7ad1f7.png)

**Foundry Information**

![image](https://user-images.githubusercontent.com/79543184/167693909-f55099dc-2920-4414-b35c-0b2dbaadeeb4.png)

**Browser (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome 
 - Browser Version: 101.0.4951.54

**Comment by vigoren** [comment]
Hmm I have no idea why foundry would be saying 1.3.75 is newer than 2.0.1. I will look into why and see if I can fix it 

In the mean time uninstalling and reinstalling will work just fine. Uninstalling doesn't remove any settings for the module so they will all be there still when you reinstall. That said making a backup of the world is always a good idea if you are worried about data loss 😁

**Comment by Shuggaloaf** [comment]
Yeah I thought it was pretty odd also.  And yes, I backup *religiously*! haha

**Comment by vigoren** [comment]
Please read these release nots about why this is happening https://github.com/vigoren/foundryvtt-simple-calendar/releases/tag/v2.0.4

The fix is to uninstall and reinstall Simple Calendar to get at least version 2.0.4 installed. After that this issue should not happen again.
Uninstalling and reinstalling the module will not remove any of your saved settings so there will be no data loss in doing so.

A quick explanation:
This has to do with the older versions of Simple Calendar having a v in front of the version number (eg v1.3.75) and the newer version not having that v (eg 2.0.4).
When doing the comparison of the first digits of the version, Foundry always treats one that starts with v as the newest version. Sadly there is nothing I can do now to fix this other than instruct people to Uninstall and Reinstall the module to get the latest version.

**Comment by Shuggaloaf** [comment]
So this is happening to everyone then? I'm honestly surprised no one had mentioned it. There were at least a few issues from people on the new version but I guess everyone just grabbed the zip. 

No worries about the uninstall/re-install. I figured that's would be the route I'd have to go anyway but I'm glad I brought it up now since it isn't just a unique issue. 

I was going to close but I can imagine others may try to update through FVTT and come straight to issues (and possibly not check for closed issues) and therefore not see the release notes.  I'll leave it up to you to close or not. 

Thanks for the help Vigoren!
