### ISSUE TITLE
[QUESTION] Where is data stored?

### ISSUE THREAD

**Issue by JacopoDeAngelis** [vigoren/foundryvtt-simple-calendar#324]
I'm encountering a problem with simple-calendar, for some reason foundry didn't update it since 1.3.62, and now updating it the calendar can't open because of some corrupted data (example in the footer).
I'd like to delete all my calendars from the files storing them but I can't find them, I tried deleting the entry in settings.db but for some reason it keeps appearing back.

Where can I find the saved file/entries?

e.g.
![immagine](https://user-images.githubusercontent.com/45501385/169410713-58afc540-b9ed-4049-bdfa-f8065eed6378.png)

**Comment by vigoren** [comment]
That does not look like you are running the latest version of Simple Calendar. Could you try uninstalling and reinstalling the module to see if that helps the issue? (No data is lost in that process)

**Comment by vigoren** [comment]
Are there any errors in the browsers console?

The data is stored in the settings.db but you would have to stop foundry, edit the file, remove every line associated with Simple Calendar, then restart foundry.

The lines that are associated with simple calendar will have `foundryvtt-simple-calendar` in them somewhere. Because of how foundry stores data there is likely to be more that one line.

**Comment by JacopoDeAngelis** [comment]
This is really strange, I tried one last time to send you the log and this time the migration popup appeared, it never did.
![immagine](https://user-images.githubusercontent.com/45501385/169645712-cccdb2cd-04de-4e57-805b-8489a61ff087.png)
So I guess it's solved now, thanks for your help!
