### ISSUE TITLE
[QUESTION] New UI vs classic, Data update?

### ISSUE THREAD

**Issue by MarkPearce** [vigoren/foundryvtt-simple-calendar#326]
Any chance to restore the previous UI?  The new themes are really bad, with drop shadows, poor color selection and contrast ratios. its not as bad with 'classic' theme.

Circles around each day adds unnecessary visual noise. The addition of the sliding panel, just adds extra steps to viewing notes.

are the data models still compatible to the old version?, I'd roll back....

**Comment by vigoren** [comment]
Sorry to hear that you do not like the new design.

There is no way to use the old design in the newest version of the module. 

You can install an older version of Simple Calendar to get the old design back but I will not be updating them and it may not be compatible with newer versions of foundry so that may be a risk in using it. The oldest version that contains the UI you seem to like would be [1.3.75](https://github.com/vigoren/foundryvtt-simple-calendar/releases/tag/v1.3.75) You can download the zip file and manually install it.
