### ISSUE TITLE
[FEATURE] Moon Phases

### ISSUE THREAD

**Issue by vigoren** [vigoren/foundryvtt-simple-calendar#34]
Look into the ability to set the phases of the moon.

**Comment by LadySaga** [comment]
Oh, if you do this I'd like to add one thing! Let the lunar cycles have at least two digits!
Why? Well, I run most of my games in the well known Forgotten Realms, and their moon Selune has a lunar cycle of 30.45.. so without the decimals the moon phases will be way of.
So that would be super-swell! :D

**Comment by vigoren** [comment]
That is good to know and will keep this in mind when adding it. Thanks!

**Comment by riccisi** [comment]
Could you consider adding more than one moon? (each with its phases). In Dragonlance-type campaigns, there are 3 moons and their phases affect the game mechanics. 
Thanks anyway.

**Comment by vigoren** [comment]
This has been added in version 1.2.0. It does support decimal places for cycle length as well as multiple moons,
