### ISSUE TITLE
Note Migration Failed Stuck Spinning [BUG] 

### ISSUE THREAD

**Issue by PhluXx1** [vigoren/foundryvtt-simple-calendar#361]
Hi, 

I upgraded from Version v1.3.75 to Version 2.0.30 I received the V1 to V2 popup window and the first two checks were ticked green. 

The third migrating notes to journal entry process was stuck with a spinning wheel for hours, eventually I relaunched the server, the popup didn't open again and nothing has migrated over and I'm missing a years worth of calendar notes. 

Can you please help or advise me how I can import the notes?

**Comment by PhluXx1** [comment]
Also it opens the calendar now every time I open the game.

**Comment by vigoren** [comment]
Sorry to hear you had a bug with the migration.

It sounds like it had an issue processing your notes and covering them to journal entries. No worries all of your note data is still there.

To start you can re run the migration by running this code in the browser console.

Hit F12 and this should open up the developer console. There should be a tab (or section) labeled console. In there paste this text and hit enter `SimpleCalendar.api.runMigration()`

This will cause the migration dialog to open again and run the migration. If the migration gets stuck an error should be logged to the console. If you can share that error with me it can help figure out what went wrong.

Alternatively if you wish you can share your  settings.db for that world with me and I can see what's going on. This article, https://foundryvtt.com/article/user-data/ , shows where the world data is stored. Under the world folder there will be a folder for the world that is having the issue and in that folder will be the settings.db


As for Simple Calendar opening every time you load that is a new setting in version 2. You can turn it off in simple calendars configuration or under the module settings. The setting is called "open on load". More details and other settings can be seen here 
https://simplecalendar.info/pages/docs/global-configuration/settings.html#client-settings

**Comment by PhluXx1** [comment]
That worked thanks. Had intermittent internet drops and was monitoring the console if I had a connection drop and then reestablish connection the process wouldn't kick off again. So I had one of my players with more stable internet do it for me, once he did it it finished and got it sorted. Thanks for the support and thanks for this awesome module you're a great dev.

**Comment by vigoren** [comment]
Glad that worked for you!

**Comment by BlackfishStudios** [comment]
I'm stuck with this error myself, but haven't been able to resolve by manually re-running the migration. 

There are a number of errors:
- "Cannot read properties of undefined (reading '0')
- "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
- "Error: You are accessing JournalEntry#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained with the data object directly.

I've attempted to restore from backup (which works great on the old version), and re-attempted the upgrade from v1 to v2 again. No dice. I am wondering if this upgrade will only work on foundry 10, and I've already moved onto foundry 11. I wasn't aware this was out of date until a recent compatibility notification, because I was stuck on an older version, but it was reporting it was up to date.

I'm betting that this is mostly a me problem since my version issues are not the typical upgrade path.

Short of manually re-typing the old notes/dates, then manually creating them in the new version, I'm wondering if there's anything else I can do. I'm wondering if there is a way to export the old note content into a txt or json, or any somewhat readable format to make the transition easier.

**Comment by vigoren** [comment]
@BlackfishStudios sorry you are having migration issues. The good news is that all the data is still there in foundry 11 we just need to get it

The migration should work, but there may be a bug in in foundry version 11. What would help me, if you are comfortable with doing so, is send me your world backup so I can try on my computer and see what's going on in more detail. If not (which is ok) it will just take me a bit to reproduce the issue and try to fix it.

If you are ok with sending me the world backup you should be able to attach it in a GitHub comment or send it to me on discord (my name on there is vigorator).

If you don't mind making a new issue for this as well that would be great.

We will get this sorted out!
