### ISSUE TITLE
[FEATURE] Support for Ernie's Modern UI

### ISSUE THREAD

**Issue by weepingminotaur** [vigoren/foundryvtt-simple-calendar#364]
Currently, Simple Calendar does not display correctly and is almost nonfunctional while running Ernie's Modern Ui. Not sure if this is a SC issue or an Ernie's issue, but I thought I would request that SC play nice with Ernie's Modern UI if at all possible. Thank you for this wonderful module!

**Comment by vigoren** [comment]
It looks like that module has a bunch of adjustments for modules (Simple Calendar included).

Simple calendars would be out of date since the 2.0.0 release.

I can look to see if it would be a quick fix on my end.

The alternative would be creating a simple calendar theme to match that UI theme. I just introduced system specific themes so I'm not sure if I want to add UI themes to that list just yet. It would be possible for Ernie to add that theme themselves to my module but not sure if they want to do that. Plus I haven't finished the documentation for how to do that yet.

I will update once I've had a chance to look into it more.

**Comment by weepingminotaur** [comment]
Thank you for the quick response! I appreciate it.

**Comment by vigoren** [comment]
It wasn't a quick fix but it wasn't a very difficult one. Version 2.1.10 should work great with Ernie's UI.

There is no matching theme but maybe one day!

**Comment by weepingminotaur** [comment]
Thank you so much!!
