### ISSUE TITLE
[QUESTION] Is it possible to get the current date and/or time formatted?

### ISSUE THREAD

**Issue by mouse0270** [vigoren/foundryvtt-simple-calendar#400]
I am trying to figure out how to get the current date formatted how the user has entered via Simple Calendar. I'd also like to get the current time formatted. I tried to look through `SimpleCalendar.api` but none of these seem to return a formatted date or time.

I guess I can get them all separately and then format them myself, but I also don't know where the users choose format is saved?

**Comment by vigoren** [comment]
There are a few ways through the API to get the formatted date/time or to format it your self.

If you just want to get the current date/time formatted to match what the user has configured in Simple Calendar the easiest way is to do this:
`const currentDate = SimpleCalendar.api.timestampToDate(SimpleCalendar.api.timestamp());`

The result will have a bunch of details though for the formatted date portion will be under `currentDate.display.date`. The formatted time portion will be under `currentDate.display.time`. Both of these values will be formatted to match what the user has set in Simple Calendar.

More details about what the timestampTpDate function returns can be found here https://simplecalendar.info/functions/SimpleCalendar.api.timestampToDate.html


If you want to format a specific date and time yourself you can use [`SimpleCalendar.api.formatDateTime()`](https://simplecalendar.info/functions/SimpleCalendar.api.formatDateTime.html). It doesn't take in a timestamp but rather an object with the date/time set in it. These values can be set manually (if you know a specific date you want formatted) or could be pulled out of the result of the `timestampToDate` function. The difference with this function is that you can specify your own format you want to apply to the date and time, using [these format rules](https://simplecalendar.info/pages/calendar-configuration/index/display-options.html#datetime-formats), to get it to look how you want. Otherwise it will default to using what is set up in Simple Calendar.

**Comment by mouse0270** [comment]
Funny timing, I just figured this out:
```
TASKBAR.addToSystemTray({
	id: 'simplecalendar',
	icon: 'fa-solid fa-calendar-range',
	title: '',
	classes: 'simplecalendar',
	html: `<div class="time">${SimpleCalendar.api.timestampToDate(SimpleCalendar.api.timestamp()).display.time}</div>
	<div class="date">${SimpleCalendar.api.timestampToDate(SimpleCalendar.api.timestamp()).display.date}</div>`,
	onclick: (elem, data) => {
		SimpleCalendar.api.showCalendar();
	}
});

Hooks.on(SimpleCalendar.Hooks.DateTimeChange, (data) => {
	TASKBAR.#SYSTEMTRAY['simplecalendar'] = mergeObject(TASKBAR.#SYSTEMTRAY['simplecalendar'], {html: `<div class="time">${data.date.display.time}</div>
	<div class="date">${data.date.display.date}</div>`}, { inplace: false });
});
```

I still think it would be useful to have something like `SimpleCalendary.api.getFormatedDisplay()` that would essentially return 
`SimpleCalendar.api.timestampToDate(SimpleCalendar.api.timestamp()).display`

As a developer who would usually only want to display the data in a useful way and not manipulate it, it would be useful to just get the user-friendly formatted date easily.

**Comment by vigoren** [comment]
In the most recent version of Simple Calendar (2.1.58) I added a few new API functions. One of which is `SimpleCalendar.api.currentDateTimeDisplay()`, which returns the display data for the current date. That should meet your need for a simpler function to call.
Thanks for the suggestion!

**Comment by mouse0270** [comment]
Thank you so much!!!
