### ISSUE TITLE
[FEATURE] Restore quick access time advancement buttons (at least in compact mode)

### ISSUE THREAD

**Issue by teroparvinen** [vigoren/foundryvtt-simple-calendar#418]
I've been using simple calendar in my campaign its whole duration and it has become a module I have a hard time living without.

I just recently ported most of my own modules to version 10 and changed my campaign over, and with that simple calendar was updated from 1.3 to 2.1. I noticed the UI changes and was... shocked to say the least.

The dropdown-based time adjustment mechanism feels super cumbersome compared to the quick access of the previous time advancement buttons. Right now I'm fanatically scrambling to find a screen shot of the previous UI to replicate it in a work around module.

The PCs stop for a moment to check if they can hear footsteps (+1 round), they look for secret doors (+5 min), you forgot to advance time while they were rummaging around a store room (+15 minutes. So often +15 minutes), they take a short rest (+1 hour), they walk to the next town (a couple of clicks on the +1 h button)... Time advancement is something that **always** comes on top of all the other issues you need to track while running a game. You don't want to stop and take time to do it.

To be honest, I never used the time reversal buttons in compact mode. Both times I had to undo something I just switched to full and used the extended controls there (which are missing as well 😮‍💨).

I hope you don't take the critique here the wrong way. I think this module is great and I'm panicking because I lost my tools. I'm all for making changes when necessary. I just feel that this change is detrimental to the user experience.

**Comment by vigoren** [comment]
Critiques are welcome, no worries there!

So we have some context of how the old view looked I have screenshots of the original expanded and compact view
![image](https://user-images.githubusercontent.com/1746488/205149018-a449e80d-65fc-4f7f-a109-9e3cf75ef290.png)
![image](https://user-images.githubusercontent.com/1746488/205149506-da7ec6bd-7276-4e54-abd4-a979682550aa.png)


With that in mind I will cover my reasoning for the changes I made. 

My main goal was to make the overall dialog size smaller, this was one of the bigger complaints I had received. On the old expanded view the time and date changing buttons took up a huge amount of space (about the same amount as the actual calendar). That coupled with there being a few requests to add additional ways to increment time (by round the most popular) that makes the list of time values that can be changed large: Year, Month, Day, Hour, Minute, Round, Second.

I liked how the time unit selector looked and functioned on the old expanded view but having 7 words next to each other takes up a lot of horizontal space (not to mention how large some of these words can get when translated into other languages). 

So my thought became to show one time unit type at a time with the ability to open a dropdown to select different options. Next to that selector it was easy to add buttons for moving that time value forward and backwards.

This kept that overall "Date/Time Changing" control small enough that it was easy to add buttons to quickly change the time of day to midnight, sunrise, noon or sunset (which was another popular request).

Now that large date and time changing section on the old expanded view was nicely compacted into a size that can fit below the calendar.


For the compact view, the old one I only offered the ability to advance time by certain amounts (which is nice and easy I agree). My thought though was this overall smaller Date/Time changing control can actually fit in the compact mode giving the GM the full control of changing the date and time forward and back by any amount so why not offer it there as well.

That was my rational and how I got to the current design of those controls. They may not be the best but overall people seem to like them (at least this is the first critique I have heard of those controls specifically)

<hr/>

What I gather from your comment is that the biggest pain point you are facing is having to switch unit types then adjusting the time, especially in the compact view. Perhaps I can have some sort of way to customize the buttons on the compact view to do what each player wants rather than what I think they want.

I don't see my changing how the expanded view works as I can't really think of a better way to show that many (potentially more) date changing options in a way that doesn't take up a huge amount of space.


Speaking of the new expanded view... 

> I just switched to full and used the extended controls there (which are missing as well 😮‍💨).

Maybe the buttons of that control are not clear enough but the single chevron button will move that time unit by 1 and the double chevron button will move that unit by 5. So that should cover the same functionality that was available in the previous version, just trimmed down a bit.

**Comment by teroparvinen** [comment]
Thanks for the detailed reply. I generally agree with your ideas about the expanded view, the time control layout there is not such a big deal. I see the expanded view as mostly the main calendar view (the compact view being the main time of day view) and not having the huge control block does generally help. Also any adjustments I personally make here are when I have to fix something like having pressed the 1h button when I intended to press the 1min button and so rare that there is no sense making a big deal out of it.

From the screenshot I can also tell I already forgot what the buttons actually were... I would personally prefer something like 1 round/1 min/5 min/15 min/1h + dawn/midday/dusk/midnight. The reasoning is that as you make adjustments, the need for absolute precision goes down (the party starts studying some books they found last night when they finish the long rest for the night, you adjust the time to 2pm, not 02:08:45 for example) and every meaningful adjustment is done with a couple of clicks: Dawn to 2pm: Midday, +1h, +1h. Go forward half an hour: +15min, +15min. Two and a half hours: +1h, +1h, +15min, +15min etc.

The other issue is that the compact view is not actually more compact than the previous one 

![image](https://user-images.githubusercontent.com/1235386/205224202-24dd3d82-db31-45b9-b50d-413f4414536a.png)
This is just a couple of pixels smaller in height and way wider.

Here's a quick hack job I did in case it gives you some ideas:

![image](https://user-images.githubusercontent.com/1235386/205227535-2090da17-140b-4a5b-b4c7-4cba0d2b1d84.png)

(The note buttons lost their colors, which wasn't really intentional but...)

I agree that customization is probably the best way to go. Maybe you could just offer a select option and a couple of layouts for the blue time control buttons (in compact view)? And another suggestion would be to make most of the elements in the compact view optional in the settings. I would personally hide the play/stop buttons and the season.

**Comment by vigoren** [comment]
I have a few personalization options to look at adding so I will add these to the list!

Thanks for the feedback.

**Comment by vigoren** [comment]
Sorry this took a bit to get out the door but in version 2.1.73 I updated the look and feel of the compact view to be a little more compact and, I think anyway, better looking over all.

I also added a new setting [Compact View Date/Time Control Layout](https://simplecalendar.info/pages/calendar-configuration/index/display-options.html#compact-view-options) under the Display Options that allows you to choose from the full date/time controls (like how it currently is) or to choose the Quick Increment layout that provides buttons for increasing the time by 1 Round, 1 Minute, 5 Minutes, 15 Minutes, 1 Hour.
