### ISSUE TITLE
[BUG] Freezes Foundry When Adding Or Deleting Notes

### ISSUE THREAD

**Issue by PhluXx1** [vigoren/foundryvtt-simple-calendar#419]
I upgraded a few months ago from v0.8.9 to the last version of v9 at the time I had issue importing entries from the old Simple Calendar version to 20.0.30. I submitted an issue and you were able to help me launch the importer which failed and closed last time. This worked and I was able to get my calendar entries imported successfully.

My problem is that SimpleCalendar has not worked properly for me since then. When I try to add an entry or edit it this causes Foundry to freeze but not fully, the pause wheel still rotates I just can't interact with anything as if waiting for SimpleCalendar to finish. I've had the console window open and it throws no errors or warnings.

Is there a fix for this? Or Is there anyway I can reset it or clear the cache so as to install the module fresh then import the notes?

**Foundry Information**
 - Foundry Version: v9 build 280
 - Game System: DnD5
 - Simple Calendar Version: 2.0.30

**Browser (please complete the following information):**
 - Browser Tried chrome, operagx, firefox

**Comment by vigoren** [comment]
There shouldn't be any freezing when adding a new note to the calendar. Under the hood notes are just journal entries in Foundry in a hidden folder.

If you want to try from fresh what you can do is this:

- Under Simple Calendars configuration go to the Import/Export tab and click the export button. This will generate a file with all of your calendar notes and settings. Save that file somewhere safe.
- Still in the configuration go to the Settings tab (the first one) and turn on the setting "Show Notes Folder". You will then need to refresh the page.
- Once the page has been refreshed and you are back into your world there should be a new notes folder visible under the Journal Tab. This directory will be called "_simple_calendar_notes_directory".
- Under this folder is every note in your calendar, to start fresh you will need to delete all the notes under this directory.
- With all the notes deleted you can uninstall the module, though this isn't specifically needed.
- Reinstall the module if you did uninstall it.
- Open up Simple Calendars configuration and go back to the Import/Export tab.
- Under the import section choose the file that you saved earlier.
- Click the Import button and it will start importing everything back into your world.
- Once it is done then you will have everything set back up.

Hopefully that helps any issues you are seeing.

If not I would be curious if the lag happens when Simple Calendar is the only module active (to rule out other modules interfering)

**Comment by PhluXx1** [comment]
Thanks for the support you're always super helpful. Looks like a module compatibility issue. I disabled all of the modules and tried SimpleCalendar solo and had no problems. Could you please see the screenshot below with my list of active modules and let me know if you see anything there that may be causing it?

![image](https://user-images.githubusercontent.com/72770484/205344671-9703140f-2feb-4e28-8517-fac88478997f.png)

**Comment by PhluXx1** [comment]
Update:
I used the fantastic module Find The Culprit to locate the problem module (great little module works like magic). 

Ultimately the problem module was [Pin Cushion](https://foundryvtt.com/packages/pin-cushion).

This mostly resolved the problem, however I still have about a 2-3 seconds of lag remaining when [Permission Viewer](https://foundryvtt.com/packages/permission_viewer), [dScryb](https://foundryvtt.com/packages/dscryb), and [Dungeon Draw](https://foundryvtt.com/packages/dungeon-draw) modules are activated but you can live with it.

Not sure if you can do anything about this or if it's an issue that the problem module developers will need to sort out but thanks for the help.

**Comment by vigoren** [comment]
Sorry got busy with a few things.

I don't see this issue in version 10 of foundry (haven't set up a version 9 instance) with any of those modules so either is issue was fixed or there is something else going on.

Do you have a large number of notes in the calendar?

**Comment by PhluXx1** [comment]
I've been running sessions in Foundry for a couple years now at least once a week so I indeed have a lot of notes. Simple Calendar is my main method of keeping track when and what happened.

**Comment by vigoren** [comment]
Sorry I didn't get back to you sooner. The other modules might be slowing things down due to the number of journal entries. 

And combined it's a more noticeable slowdown. I'll be curious to see what the other module says about the issue.

**Comment by vigoren** [comment]
Going to close this issue!
