### ISSUE TITLE
[FEATURE] Please put Simple Calendar button back on Token Controls and not Journal Notes, or give us the option to always have the calendar open

### ISSUE THREAD

**Issue by GambetTV** [vigoren/foundryvtt-simple-calendar#421]
I think I mentioned in a past report that hitting Esc on any window (such as a journal or character sheet) also closes Simple Calendar, and if I recall correctly you said you couldn't figure out how to make that not happen. I don't know if this would help, but you could look to IronMonk's Always HP module that managed to figure out how to keep their window permanently open, or even toggling it on and off in the Game Settings.

That said, if it just can't be done, then fair enough, but can you at least put the Calendar toggle back on Token Controls? I can tell you that my experience with this module has been a love/hate relationship between how amazingly useful it is and how frustrating the user experience has been. This is a module that if I could keep the window permanently open, I would want to be writing notes, keeping track of the time of day, fast forwarding every time they take a short/long rest or travel, and it would really add another level to my campaign, which is why I installed this module in the first place. But these little idiosyncrasies, where between hitting ESC closing the window, and now reopening it requires me to hit a button in the Journal Entries tab, has resulted in an overall experience where because it's just so out of sight, out of mind, I barely use the module, and I just kind of spitball at the end of sessions where I think the time should be, if I remember to do it at all.

So yeah, just some feedback! It might just be me experiencing this level of frustration and if so, then fair enough.

**Comment by vigoren** [comment]
I moved the token control to the journals section because I had several people request that it be moved out of token control as it is not for controlling tokens and the journals notes section fits better for what the calendar does.

That said I could possibly add an option to allow the user to choose where it goes in the list then people who like it under token control can have it there.

The escape issue is that when you hit escape it calls the close function for that application. You can define how the close function works for your own applications and what I have found is that other modules just disable closing all together (which is what Always HP does). But allowing someone to click close and not close when escape is pressed is not possible through that function because it doesn't know what action was taken, just that it was told to close.

All that said I could again make a setting to disable being able to close Simple Calendar at all and change the button from the sidebar toggle it open/closed instead.

**Comment by vigoren** [comment]
In version 2.1.73 I added a client setting called Persistent Open. When checked on the calendar the close button will be hidden, and escape will not close it. The button under the Journal Notes section then acts as a toggle to open/close the calendar.

I think that should cover your needs here!
