### ISSUE TITLE
[BUG] Cannot Read properties of undefined when opening Simple Calendar settings

### ISSUE THREAD

**Issue by Quercuas** [vigoren/foundryvtt-simple-calendar#424]
**Describe the bug**
When opening the settings of Simple Calendar the following error appears in the log:

Error "Cannot read properties of undefined (reading 'numericRepresentation')"
TypeError: Cannot read properties of undefined (reading 'numericRepresentation')

**To Reproduce**
1. Configure Settings
2. Go to Simple Calendar
3. Open "Simple Calendar Configuration"

**Expected behavior**
No errors to appear

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/96662470/206287672-0be0b064-743e-4194-b258-c6714faed989.png)

**Foundry Information**
 - Foundry Version: V10.291
 - Game System: DnD53
 - Simple Calendar Version: 2.1.60
 - Simple Calendar Configuration: Forgotten Realms

**Browser (please complete the following information):**
Foundry Application

**Additional context**

**Comment by vigoren** [comment]
Sorry about the super long delay in answering this (holidays were very busy).

This is a bug I haven't tracked down just yet but it doesn't affect anything. It only appears when in the configuration dialog. 
I think it only happens when changing the number of months in a year or between calendars with different months.

So nothing to worry about in terms of errors with your calendar, just a small error I need to fix.

**Comment by vigoren** [comment]
This has been fixed in version 2.3.6!
