### ISSUE TITLE
[BUG] Update Frequency speeds up the clock

### ISSUE THREAD

**Issue by LukasPrism** [vigoren/foundryvtt-simple-calendar#428]
Setting the Update Frequency actually has the effect of increasing the Game Seconds per Real Life Seconds value.

1. Go to 'Update Frequency'
2. Put in a value of 10 and Save
3. Observe how the clock now updates at the rate of 10 seconds for each real second

I've tested this with no other modules activated.

Thanks for an amazing module, FVTT wouldn't be the same without it!

**Comment by vigoren** [comment]
What I have found is that these settings do work but not if you change them while the clock is running. If you stop the clock, then set the "Update Frequency" to 10, then restart the clock it will work as expected.

I will add a fix for changing that value while the clock is running so that it will start updating to the entered value after the configuration is saved.

**Comment by vigoren** [comment]
This issues was fixed in version 2.1.73!
