### ISSUE TITLE
[FEATURE] Ability to choose location of "note for year"

### ISSUE THREAD

**Issue by jonepatr** [vigoren/foundryvtt-simple-calendar#44]
**Is your feature request related to a problem? Please describe.**
If the year is one long month (as in the Traveller game), the calendar gets very long and is quite annoying to scroll to the bottom each time one wants to view something.

**Describe the solution you'd like**
Let it be an option to see the calendar events on the right side below the current date controls. 

**Describe alternatives you've considered**
Have it above the calendar, but I don't think that will work super well. 

**Additional context**
<img width="622" alt="Screenshot 2021-04-04 at 12 56 30" src="https://user-images.githubusercontent.com/1084164/113506446-39cdc200-9545-11eb-994b-acf3d31e2242.png">

**Comment by vigoren** [comment]
Ah good points, I wasn't aware of the traveler calendar being just 1 month. I will look into ways to make that more usable.

**Comment by vigoren** [comment]
Rather than moving the event list around I have changed is to the calendar has a maximum height. If the list of days exceeds this maximum height (which in the case of the Traveller it does) the list becomes scrollable so you can scroll to see the other days.

If the current or selected day falls down the list of days the calendar will automatically scroll the list of days down so it is visible.

I think this approach is the best solution for now. At the very least it makes the calendar usable.

I have also added some other changes to better incorporate the Traveller calendar. First I added it as a predefined calendar so set up should be easy. The second change is adding the ability to offset the day number the month starts on. In doing research on this calendar I saw that day 1 of the year is a holiday that doesn't affect the days of the week for the rest of the year. To me that makes sense to make a holiday month that is intercalary and has one day. Then with this new offset the second month (the rest of the year) can start on day 2 and continue on so the days properly line with the days of the week that they should fall on.

These changes should be coming out later this week after I finish a couple of other things up and put out a release.

**Comment by jonepatr** [comment]
Wow, thanks!! This sounds great! :D

**Comment by vigoren** [comment]
This is now live in the latest release. Let me know how it looks and if there are any issues with it.
