### ISSUE TITLE
[FEATURE] More control over time in "Quick Increment" mode

### ISSUE THREAD

**Issue by gsterling** [vigoren/foundryvtt-simple-calendar#447]
**Is your feature request related to a problem? Please describe.**
Quick Increment is a nice new feature. I was always annoyed when I had to adjust time switchting between 30 minutes and 2 hours.

But I think it could add some more features without compromising on the minimal look.

**Describe the solution you'd like**
##### Reverse time
I'd like to be able to reverse time, either when setting up a scene to the perfect time or I accidentally incremented it too much.
You should be able to decrease time when pressing `Ctrl + Left Mouse` on the buttons by that amount it would normally increase the time. Add a tooltip indicating if you are increasing or decreasing if you'd click now.

##### Bigger steps
I'd liked the 1 step oder 5 steps from "Full Controls" mode. Can you enable this again with let's say `Shift + Left Mouse` on the buttons? So Shift + left click on "1h" should increment it by 5 hours? Again with a tooltip explaining, that you would now increment time by a factor of 5. This would make "5m" a bit pointless though. I'd understand if you'd want to keep it, to not force players to use this feature, but I'd personally wouldn't mind to get rid of it in favor of the 5 steps per click. So it'd only show "1r", "1m", "15m", "1h" and maybe then even add "1d".

##### Mix both above features
`Shift + Ctrl + Left Mouse` should decrease the time by 5 steps per click.

**Describe alternatives you've considered**
##### Use the mousewheel to change time
Alternatively you could add both options to the mouse wheel. Hover over one of the buttons and scrolling up increases the time for the desired step for each tick of the wheel, scrolling down decreases it. It would be an increadible fast and intuitive way to change the time and be as precise or fast as you'd want.

**Comment by vigoren** [comment]
Yeah I can see these options being useful and including a key click would make it possible without cluttering up the display with more options.

I will look into it!

**Comment by vigoren** [comment]
@gsterling I have updated this in version 2.1.80 so that holding the control key down will allow you to subtract the time value clicked from the current date and time. I have also added the shift key so that you can increase the amount of time added for each button  from `1 round, 1 minute, 5 minutes, 15 minutes, 1 hour` to `5 rounds, 5 minutes, 20 minutes, 45 minutes, 5 hours`. The shift and control keys can be combined to subtract a larger amount of time from the current time.

@agedusilicium Sorry I didn't see this comment, I have thought about adding a view that would allow a user to specify the buttons but haven't had the time to create that. When I add that I think that will cover what you need.
