### ISSUE TITLE
[BUG] Documentation links broken

### ISSUE THREAD

**Issue by Scarjit** [vigoren/foundryvtt-simple-calendar#464]
**Describe the bug**
Any documentation link is broken

**To Reproduce**
1. Open the configuration
2. Click on any documentation link

**Expected behavior**
Documentation should open

**Screenshots**
![chrome_D1afTCs1C9](https://user-images.githubusercontent.com/6317420/218306560-ecd7d402-6036-4209-b54e-a00f7f76731b.gif)

**Foundry Information**
 - Foundry Version: [e.g. 0.10.290]
 - Game System: [e.g. DSA5/TDE5]
 - Simple Calendar Version: [eg 2.1.80]
 - Simple Calendar Configuration: [none]

**Browser (please complete the following information):**
 - Chrome

**Additional context**

**Comment by vigoren** [comment]
That version of Simple Calendar looks like it is quite old (v1.3.75)
The documentation was moved from GitHub to its [own site](https://simplecalendar.info/index.html) a while ago.

Due to an update bug when on version 1.3.75 or earlier. Follow these steps to get the latest version:

- **Uninstall Simple Calendar**: In the module management section of FoundryVTT uninstall the module. This is a safe procedure as no data (notes, configuration settings) is deleted when uninstalling.
- **Reinstall Simple Calendar**: In the module management section of FoundryVTT reinstall the module, the new version of Simple Calendar should be 2+.
- **Relaunch Your World**: Go back into the world that was having the problem, you will see a dialog informing you of a data migration. Once that has finished all your information will be available, the module will work, and you are ready to use the calendar!

**Comment by Scarjit** [comment]
Got it, that fixed the issue.

**Comment by Scarjit** [comment]
![chrome_dCgrsS7jQw](https://user-images.githubusercontent.com/6317420/218324265-c8186a90-d66b-4885-9b12-df7a90d8bd1c.png)
This link is still wrong

**Comment by vigoren** [comment]
I will check that one out. It should link to this page https://simplecalendar.info/pages/calendar-configuration/index/display-options.html#datetime-formatting


Simple calendar also has [themes](https://simplecalendar.info/pages/docs/using-sc/index/themes.html) that you can set to have it match your system better if you wish.
