### ISSUE TITLE
Cannot edit calendar [BUG] 

### ISSUE THREAD

**Issue by DiddyDragon** [vigoren/foundryvtt-simple-calendar#469]
**Describe the bug**
When I edit the calendar to make my own custom calendar, when I press the save configuration button nothing happens

**To Reproduce**
1. Open the Simple calendar on a world
2. Click on Configure
3. Input custom information
4. Click the save configuration button

**Expected behavior**
I expected the calendar to save my custom calendar but it does not. Even when I close and reopen the calendar it resets the configuration to default.

**Screenshots**
![image](https://user-images.githubusercontent.com/126519394/221684280-e87fdd83-5b00-49fd-b0d0-d1835a163d7c.png).

**Foundry Information**
 - Foundry Version: Version 10 Build 291
 - Game System: Pathfinder 2nd Edition
 - Simple Calendar Version: 1.3.75
 - Simple Calendar Configuration: As seen in screenshot

**Browser (please complete the following information):**
 - In app/No Browser

**Comment by vigoren** [comment]
This is due to an update bug when on version 1.3.75 or earlier. Follow these steps to get the latest version:

- Uninstall Simple Calendar: In the module management section of FoundryVTT uninstall the module. This is a safe procedure as no data (notes, configuration settings) is deleted when uninstalling.
- Reinstall Simple Calendar: In the module management section of FoundryVTT reinstall the module, the new version of Simple Calendar should be 2+.
- Relaunch Your World: Go back into the world that was having the problem, you will see a dialog informing you of a data migration. Once that has finished all your information will be available, the module will work, and you are ready to use the calendar!

**Comment by geoidesic** [comment]
Uninstalled version 1.x and re-installed to get v2.x. Problem goes away. 
(I don't seem to have the option to close this issue?)
