### ISSUE TITLE
[BUG] Changing to a pre-set calendar type doesn't update the displayed calendar

### ISSUE THREAD

**Issue by LonePaladin** [vigoren/foundryvtt-simple-calendar#495]
**Describe the bug**
When you change to a pre-set calendar (such as the "Golarion PF2" one), you get a warning that it will override the current settings, and the month and week listings change in the settings window, but nothing changes in the calendar display.

**To Reproduce**

1. Click on the Calendar button
2. Click on Configure
3. Select a Predefined Calendar
4. Click on Apply
5. When the prompt appears, warning that it will override everything, click on Apply
6. Click on Save Configuration
7. Close the configuration window
8. See that the calendar has not changed

**Expected behavior**
I expected to see the date change, along with the names of the months and days of the week

**Foundry Information**
 - Foundry Version: 10.291
 - Game System: Pathfinder 2E 4.11.2
 - Simple Calendar Version: 1.3.75

**Browser (please complete the following information):**
 - Default Foundry client

**Comment by vigoren** [comment]
This is due to an update bug when on version 1.3.75 or earlier. Follow these steps to get the latest version:

- Uninstall Simple Calendar: In the module management section of FoundryVTT uninstall the module. This is a safe procedure as no data (notes, configuration settings) is deleted when uninstalling.
- Reinstall Simple Calendar: In the module management section of FoundryVTT reinstall the module, the new version of Simple Calendar should be 2+.
- Relaunch Your World: Go back into the world that was having the problem, you will see a dialog informing you of a data migration. Once that has finished all your information will be available, the module will work, and you are ready to use the calendar!
