### ISSUE TITLE
Simple Calendar is not saving any of my custom names 

### ISSUE THREAD

**Issue by KTSirDrinksAlot** [vigoren/foundryvtt-simple-calendar#535]
When I go to modify the names of the days of the month and week and save configuration, it doesn't keep those names. I make sure to save configuration. I have went through all setting to see if there are any other issues and I can find none. Can you help remedy this?

**To Reproduce**
1. Go to Month settings
2. Add new names to month name sections
3. Save configuration
4. exit and see the calendar is not reflecting the new changes

**Expected behavior**
The calendar to reflect the month name and weekday name changes

**Foundry Information**
 - Foundry Version: 11.308
 - Game System: DnD5e
 - Simple Calendar Version: 1.3.75
 

**Browser (please complete the following information):**
 - Browser- FoundryVTT program/CHROME
**Additional context**
Deemed screenshots will not add better context when changes reset to default settings after changed have been saved.

**Comment by vigoren** [comment]
This is because you are on a really old version of Simple Calendar. Due to an update bug when on version 1.3.75 or earlier you need to follow these steps to get the latest version:

**Uninstall Simple Calendar**: In the module management section of FoundryVTT uninstall the module. This is a safe procedure as no data (notes, configuration settings) is deleted when uninstalling.

**Reinstall Simple Calendar**: In the module management section of FoundryVTT reinstall the module, the new version of Simple Calendar should be 2+.

**Relaunch Your World**: Go back into the world that was having the problem, you will see a dialog informing you of a data migration. Once that has finished all your information will be available, the module will work, and you are ready to use the calendar!

**Comment by KTSirDrinksAlot** [comment]
Thank you that worked. My players have been begging for an updated calendar system and I'm glad its working again. Thanks for the help!!!
